using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;

[Generator]
public class JenxSimpleWelcomeGenerator : ISourceGenerator
{
    public void Execute(GeneratorExecutionContext context)
    {
        var myAutoGeneratedCode =
            $@"
using System;
namespace Jenx.CompileTimeGenerated
{{
    public static class JenxWelcome2
    {{
        public static void SayHello()
        {{
            Console.WriteLine(""My personal welcome"");
            Console.WriteLine(""*********************"");
            Console.WriteLine(""Hello from generated code from jenx.si"");
            Console.WriteLine(""App compile date/time: { DateTime.Now }"");            
            Console.WriteLine(""App excute date/time: "" + DateTime.Now.ToString());

            Console.WriteLine(""Compiled on: { System.Net.Dns.GetHostName() } machine""); 
            Console.WriteLine(""App executed on: "" + System.Net.Dns.GetHostName() + "" machine""); 
        }}
    }}
}}";

        context.AddSource("jenxWelcome", SourceText.From(myAutoGeneratedCode, Encoding.UTF8));
    }

    public void Initialize(GeneratorInitializationContext context)
    {
    }
}
