/*
//This class was autogenerated at 01.03.2022 14:16:56
using System;
public class IMovableAdapter : IMovable
{
Tanks_Game_Core.GameObject obj;
public IMovableAdapter(Tanks_Game_Core.GameObject obj) { this.obj = obj; } 
public IMovableAdapter() { }
public System.Numerics.Vector3 getPosition()
{
return IoC.Resolve<System.Numerics.Vector3>("IMovable.Position", obj);
}
public System.Numerics.Vector3 setPosition(System.Numerics.Vector3 newValue)
{
return IoC.Resolve<System.Numerics.Vector3>("IMovable.Position.set", obj, newValue);
}
public System.Numerics.Vector3 getVelocity()
{
return IoC.Resolve<System.Numerics.Vector3>("IMovable.Velocity", obj);
}

public void finish()
{
    IoC.Resolve<object>("IMovable.finish");
}
}
*/